[dev]
  command = "npm run dev"
  publish = "dist"
  port = 8888 

[[redirects]]
  from = "/prive/*"
  to = "/"
  status = 404
  force = false

[[redirects]]
  from = "*"
  to = "/"
  status = 404
  force = false